### ISSUE TITLE
implement automerge-repo sync

### ISSUE THREAD

**Issue by heckj** [automerge/MeetingNotes#34]
Match the updates to automerge-repo and implement the capability to sync Automerge documents to an Automerge-sync server.

This would add at least a few dependencies:
- [x] websocket support for the transport
- [x] possibly bs58 for encoding document IDs (16 bytes of random data) as UTF-8 strings
  - [description of BS58 encoding algorithm](https://en.bitcoin.it/wiki/Base58Check_encoding)
  - [JavaScript Code](https://github.com/bitcoinjs/bs58check)
  - Swift Packages:
    - https://swiftpackageindex.com/cloutiertyler/Base58String
    - https://swiftpackageindex.com/keefertaylor/Base58Swift <— looks to be the more complete/checking incl
- [ ] look into URL support for an automerge://... URI (conceptual - proposed in dev, but ?? implemented)

Example sync server code at https://github.com/automerge/automerge-repo/blob/main/examples/sync-server/package.json, with live endpoints that are available

**Comment by alexjg** [comment]
Two thoughts:

1. I don't want to take on a dependency for the bs58 stuff so I may add an implementation of it to `automerge-rs` directly. I would also accept PRs to do this before I get to it.
2. Instead of the websocket support I wonder if we should add a TCP implementation of the transport to `automerge-repo` and enable it on the default sync server, it seems silly to use websockets outside of a browser.

**Comment by heckj** [comment]
I'd be delighted to see any of this move into the core library (bs58 in particular) so I didn't need to canonically mess with the data representation, just wasn't sure where all that might fit into the priorities of development, so figured I could start out with it locally first, and rip it out as it became available in Rust.  I'll take a look at finding a Rust library for the same and see what a PR might look like, just still feeling like Rust isn't exactly my strength ;-)

Lots of apps use WebSocket, so I wasn't entirely fussed about it - if there's a raw TCP server implementation, I can definitely match that with Network (since I basically did that for the peer-to-peer sync included already in this app), but I didn't want to "make more work" when there's already a WebSocket implementation in place.

Side goal of all this - extract the common pieces into a library that adds onto Automerge-swift - at least what doesn't get pressed down into the core Rust library. I thought about adding this directly into Automerge-swift, but I didn't want to take on the additional dependencies for the core library, which is why I was leaning to a follow-on/build on kind of library setup for the sync.

**Comment by alexjg** [comment]
Ah I forgot that this is not inside `automerge-swift`, so taking on a new dependency is not such a big deal 🙂. I would optimise for getting something working first and I'll sort out the bs58 stuff in automerge proper in the next month or so.

Re. websockets: I guess pragmatically every sync server is going to run a websocket thing just so the browser can talk to it so maybe I shouldn't worry too much about TCP. It just ... bothers me somehow. If it's normal in iOS to jus use a websocket then yeah, we should do that.

Extracting all this into a separate companion library for Automerge-Swift (rather than putting it in core) makes sense.

**Comment by heckj** [comment]
MeetingNotes now has the sync capability enabled (with #37)

I looked into supporting automerge:// URL concepts, but the alignment is off from how Apple defines and sets up associated URL for this sort of thing, so I don't think it makes sense in this case. They're either 1) pinned to an application, or 2) pinned to a site. Multiple apps *can* support a custom URL scheme, but when two different apps declare the same URL scheme, who gets called when it's invoked is undefined. So for anyone wanting to use such a mechanism, they're better off implementing their own URL scheme specific to their app, which in turn can use the code created here to attempt to load a DocumentID from a remote WebSocket automerge-repo instance of their choice.
